name: social_share_plugin_ios

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    pull_request:
        paths:
            - ".github/workflows/social_share_plugin_ios.yaml"
            - "packages/social_share_plugin_ios/**"
    push:
        branches:
            - main
        paths:
            - ".github/workflows/social_share_plugin_ios.yaml"
            - "packages/social_share_plugin_ios/**"

jobs:
    build:
        uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
        with:
            flutter_channel: stable
            flutter_version: 3.10.0
            working_directory: packages/social_share_plugin_ios

    pana:
        uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
